### ISSUE TITLE
Add CLI tool to help admins generate keys and do test operations against a repo

### ISSUE THREAD

**Issue by heartsucker** [heartsucker/rust-tuf#107]
Currently it's a bit annoying to make ed25519 keys and there's just notes in the docs on how to shell out to `openssl` to make RSA keys. This should be wrapped in a CLI tool.

Also, some basic upload/download operations could be supported for testing.

**Comment by heartsucker** [comment]
Key generation covered in 82d6c86

**Comment by zmanian** [comment]
Right now the just puts an unrenderable bitstream into the terminal? Do you have a preference between hex and base64 encoding?

**Comment by zmanian** [comment]
For reading in keys, environment variables and/or config files?

**Comment by heartsucker** [comment]
If you read the `help`output:

```
heartsucker@pythagoras:~/code/heartsucker/rust-tuf (delegations)$ cargo run --features=cli -- -h
   Compiling tuf v0.2.0 (file:///home/heartsucker/code/heartsucker/rust-tuf)
    Finished dev [unoptimized + debuginfo] target(s) in 8.4 secs
     Running `target/debug/tuf -h`
tuf 0.2.0
CLI tool for managing TUF repositories

USAGE:
    tuf <SUBCOMMAND>

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

SUBCOMMANDS:
    help      Prints this message or the help of the given subcommand(s)
    keygen    Generate private keys and print them as PKCS#8v2 DER to STDOUT
```

It's writing the files as DER. I chose to not output files because I don't know how to properly set read permissions on Windows and didn't want to accidentally let people create globally readable private keys.

In the JSON, I'm using base64url encoding of the DER keys in SPKI format. I don't do anything with environment variables or configs yet, but if I do, I'll document what formats everything needs to be in.

**Comment by heartsucker** [comment]
Closing this for now since there are way too many config options for me to want to support all repo operations via CLI at the moment. If someone wants that, please reopen this.
