### ISSUE TITLE
Refactor delegation logic to only download delegations on-demand

### ISSUE THREAD

**Issue by heartsucker** [heartsucker/rust-tuf#113]
Currently it recursively grabs everything to prevent future replays of old metadata in the event of a snapshot key compromise. This is going to be waaaaay too much metadata even in the simple `static.rust-lang.org` case because older targets would be relegated to an archive type delegation whichi would necessitate frequently updating many delegated roles.

This is bad for local storage and bad for lots of requests / network IO.

**Comment by trishankkarthik** [comment]
Did anyone say my name thrice? No? Well, boo anyway!

Jokes aside, let me help to clarify exactly which delegations should and should not be downloaded.

**Comment by vladimir-v-diaz** [comment]
> Currently it recursively grabs everything to prevent future replays of old metadata in the event of a snapshot key compromise. 

I'm confused as to why you wanted to grab every delegated role in the first place.  Is it not enough to use the version numbers listed in the snapshot file to prevent replay attacks? 

Perhaps we should make it clearer that every version number listed in new snapshot metadata must be greater than the version number previously listed for each role?

Here's what we currently say in the spec: https://github.com/theupdateframework/tuf/blob/0fc58f63350e441a62191643b6de49158f05f2c6/docs/tuf-spec.txt#L1052-L1057

**Comment by trishankkarthik** [comment]
On Tue, Jul 18, 2017 at 2:40 PM, Vladimir Diaz <notifications@github.com>
wrote:

> Currently it recursively grabs everything to prevent future replays of old
> metadata in the event of a snapshot key compromise.
>
> I'm confused as to why you wanted to grab every delegated role in the
> first place. Is it not enough to use the version numbers listed in the
> snapshot file to prevent replay attacks?
>

I don't think he did it to prevent rollback attacks ala Diplomat. I think
it was just the simplest thing to do, and we certainly didn't help by not
making things clearer in the spec before his implementation :)

**Comment by heartsucker** [comment]
> Perhaps we should make it clearer that every version number listed in new snapshot metadata must be greater than the version number previously listed for each role?

Ha! I came to this same conclusion after I posted this. This should be sufficient, no?

Also @trishankkarthik , can you email me these papers you guys keep talking about? Might be helpful for stuff like this.

**Comment by heartsucker** [comment]
Also tagging @brson since this was one of his concerns.

**Comment by trishankkarthik** [comment]
Here's [the Diplomat paper](https://www.usenix.org/conference/nsdi16/technical-sessions/presentation/kuppusamy), which discusses how to process prioritized and / or terminating delegations to download only the delegations you need.

Here's [the Mercury paper](https://www.usenix.org/conference/atc17/technical-sessions/presentation/kuppusamy), which discusses how to use the snapshot metadata to prevent rollback attacks against all delegations, despite downloading only the delegations you need. (Audio and slides should come in a week or two.)

And here's [the latest version of the TUF specification](https://github.com/theupdateframework/tuf/blob/0fc58f63350e441a62191643b6de49158f05f2c6/docs/tuf-spec.txt#L948-L1139), which should discusses the changes from Diplomat, Mercury, and some recent TAPs.

**Comment by heartsucker** [comment]
Cool thanks.

I was using the latest version of the TUF spec, but it doesn't say anything about whether or not all metadata files need to be downloaded. I drew the conclusion that all delegated roles need to be grabbed each time because the spec doesn't say it either way, and it seemed like doing so mitigated a number of attacks.

I would still like to see the spec RFC'd into something that is absolute about what must be done and what must not be done in the whole update / download / verify process. I (in `rust-tuf`) and we (at work) have hit issues with TUF and Uptane a number of times because of the lack of clarity and undefined behavior.

Tagging https://github.com/theupdateframework/tuf/pull/455 again.

**Comment by trishankkarthik** [comment]
Sorry to hear about your pain points. I have always been a little unhappy myself with the ambiguity of the client update workflow (Section 5) of the spec, which is why I started fixing it recently.

I'll add a note about making it much clearer what to download or not. Please keep letting us know what you find.

**Comment by heartsucker** [comment]
So when I went back and re-read the spec, it turns out it was implicitly covered by the line in section 3 of the detailed workflow that says that all metadata versions in the new snapshot need to be greater than or equal to the current. Still a little ambiguous, but not like I'm not to blame.

**Comment by vladimir-v-diaz** [comment]
> 3.3.3.
> The version number of the targets metadata file, and all delegated
> targets metadata files (if any), in the trusted snapshot metadata file, if
> any, MUST be less than or equal to its version number in the new snapshot
> metadata file. Furthermore, any targets metadata filename that was listed
> in the trusted snapshot metadata file, if any, MUST continue to be listed
> in the new snapshot metadata file.

The text can be more concise.  The first sentence of 3.3.3 is way too long and increases the chance that the reader will miss an important point (i.e., that all version numbers listed in new snapshot metadata must be greater than or equal to the ones in the trusted snapshot metadata).

The detailed workflow is getting a bit long and I'm worried the reader might gloss over a few points.

**Comment by heartsucker** [comment]
> the reader

![whome](https://user-images.githubusercontent.com/3998464/28377279-91d302d2-6cac-11e7-8e1c-cab71f62636c.gif)
