### ISSUE TITLE
Terminating delegations are not handled properly

### ISSUE THREAD

**Issue by heartsucker** [heartsucker/rust-tuf#114]
Current logic is "if a delegation is marked as terminating, abort entirely," but this abort should only happen for the current branch of delegations. For example, `A` delegates to `B1` and `B2` for packages matching `*`, both non-terminating. `B1` delegates to `C1` and `C2` for `*` with `C1` terminating. Because `A` has not marked `B1` as terminating, a failure at `C1` should not prevent it from moving on to `B2`.

Source: https://www.usenix.org/system/files/conference/nsdi16/nsdi16-paper-kuppusamy.pdf

Also @trishankkarthik, this was not obvious from the spec as it is written (section `4.5.2.2`).

**Comment by trishankkarthik** [comment]
Actually, terminating delegations are meant to be a global abort in case the target is not found. This may seem counterintuitive, but the motivation for this is given in the Diplomat paper. There, the "targets" role has delegated * to both "claimed-projects" and "new-projects", but if "claimed-projects" has used a terminating delegation to "foo", then the TUF / Diplomat client must not backtrack to "new-projects" to find a missing "foo" package. This is so attackers who compromise the repository cannot fool users into installing unofficial "foo" packages.

Now, you are right that this can accidentally lead to denial-of-service if a delegator mistakenly makes a terminating delegation when that is not the intent. There are a few ways to solve this problem. One way is to introduce an option in TUF that forbids any delegatee from using terminating delegations. I feel we may need options like setting the depth and breadth of delegations anyway.

But this may not be necessary. What do you think @JustinCappos and @vladimir-v-diaz ?

**Comment by heartsucker** [comment]
Ok, so the rouge-delegation-DoS was what I was concerned about and why I thought I read that part of the spec wrong. I don't see a clean way to solve both the problems at the moment, though that could be because I'm in bed and it's pushing towards 1am. I'll have to think about this tomorrow.

**Comment by heartsucker** [comment]
Since it appears that logic described in above and in the related papers is implemented, I'm closing this.
