### ISSUE TITLE
Don't transmit precalculated keyIDs

### ISSUE THREAD

**Issue by heartsucker** [heartsucker/rust-tuf#118]
Currently keys are sent in the form `Map<KeyId, PubKey>` and the application is expected to calculate the `KeyId` from the `PubKey` and ensure it matches what was transmitted. Since the calculation can be done exactly one way, having the sender precalculate it is just wasted bandwidth. For Ed25519 keys, the key ID is ~2/3 the size of the key itself.

This means there are two options:

1. Precalculate the key ID and force the client to verify the calculated key ID 
2. Send just the key and have the client calculate the key ID

The open question is: Is there an attack that is mitigated by using 1 over 2? If so, does it open the possibility of additional attacks that were not present in 2?

Presently, I'm inclined to say that 2 is the superior choice.

**Comment by trishankkarthik** [comment]
I agree. I can't see what (1) gives over (2). The pubkey is the important bit: I'm not sure what keyid=hash(pubkey) adds.

The point about wasted b/w is a good one. @JustinCappos and @vladimir-v-diaz, is there a good reason why we need to use hashes of public keys as key ids? I understand why the keyid within a metadata file needs to be unique, but why does it need to be so globally? Here is the [relevant bit from the spec](https://github.com/theupdateframework/tuf/blob/67eb57ae1c400e2d1446889e079b0ef94ee4bb52/docs/tuf-spec.txt#L569-L572).

I understand that keys can be repeated within a metadata file, but couldn't we use plain integers instead to refer to unique keys? (Internally, we can use hashing to refer to unique keys, but that need not be exposed in the metadata.) An attacker who controls the metadata can always insert [duplicate values in a JSON dictionary](https://github.com/theupdateframework/tuf/issues/372), and it's up to the JSON parser to detect and warn about this.

Maybe there are some binding attacks, but I don't see what they are right now. What would someone gain by associating the wrong hash(pubkey) with a pubkey? It seems to me there is a hidden assumption that a TUF client updater uses a giant, global dictionary to store all pubkeys [ hash(pubkey) -> pubkey ], but is this necessary?

**Comment by heartsucker** [comment]
> is there a good reason why we need to use hashes of public keys as key ids

I think this is actually the best thing. I'm using `sha256(spki(pub_key))` and think that is the most reasonable approach to identifying keys. How else would you link a signature back to a key?

> but why does it need to be so globally

If it's not, then you could get collisions that would allow the wrong key to verify something. For example, if we did `key_id = md5(spki(pub_key))`, then you could generate some number of keys until a collision occurs and sign things falsely.

> but couldn't we use plain integers instead to refer to unique keys?

This would be so much harder to deal with and wouldn't allow external tools to identify a key without knowing about ALL metadata and all keys in ALL metadata.

The key's ID should be independent of TUF and *only* rely on the key's bytes.

**Comment by trishankkarthik** [comment]
So I agree that hash(pubkey) lets you verify signatures quickly. But that's an efficiency thing.

What is the security point of ensuring that keyids are unique globally? What does the keyid of a key of, say, the timestamp role in the root metadata have to do with the keyid of some far away delegated targets role? Again, it seems to me there is a hidden assumption that a TUF client always uses a giant, global dictionary of public keys.

**Comment by heartsucker** [comment]
> Again, it seems to me there is a hidden assumption that a TUF client always uses a giant, global dictionary of public keys.

Yes, so I don't use a global key store, but someone might, and TUF shouldn't specify how the application internally stores keys, and to this end, it would be reasonable to suggest to the user that key IDs should be `hash(pub_key_bytes)` in some way that ensures there are no collisions. Also, the key identifier (hash value, number, whatever) should be independent of where it occurs in metadata (which order it is in the `keys` field, which piece of metadata it appears in). The only way to get unique (or at least very close to) identifiers that only rely only on the key's contents is with a hash.

But also, an implementer may wish to optimize heavily and use an unsigned int to identify keys within a given context by number (or even index in an asn.1 `SEQUENCE OF`) and this might be ok. It feels wrong given how public keys are usually identified, but if done correctly it shouldn't present new vulnerabilities.

**Comment by heartsucker** [comment]
> if done correctly it shouldn't present new vulnerabilities

For the record, this sentence terrifies me.
