### ISSUE TITLE
Ensure all timestamps use ISO-8601 format YYYY-MM-DD'T'HH:MM:SS'Z'

### ISSUE THREAD

**Issue by heartsucker** [heartsucker/rust-tuf#124]
Failure to ensure this may break deterministic serialization/deserialization in the future.

**Comment by tarcieri** [comment]
Z-normalized FTW, although you might want to refer to [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) instead

**Comment by heartsucker** [comment]
Yup. This is what was intended, but I'm not positive the underlying lib does this by default when using `serde`, so I'm going to override it just to be safe.
