### ISSUE TITLE
Publish the demo CLI?

### ISSUE THREAD

**Issue by erickt** [heartsucker/rust-tuf#134]
Hello @heartsucker! You mentioned in this [comment](https://github.com/heartsucker/rust-tuf/pull/133#issuecomment-404833204) that you've written a demo CLI. I was thinking about working on one, and if you have a foundation, that's even better. Could you publish it to a branch that I could iterate on? Thanks!

**Comment by heartsucker** [comment]
Heya. I need to track down the laptop that was on because it looks like that never got pushed to GH. I'll see if I can find it.

**Comment by erickt** [comment]
Any luck finding that laptop?

**Comment by heartsucker** [comment]
Same issue as the TLA+ models. I don't think I have access to it any more?
