### ISSUE TITLE
Actually finish the TLA+ model for TUF and inclue it in repo

### ISSUE THREAD

**Issue by heartsucker** [heartsucker/rust-tuf#145]
I started a TLA+ model for TUF that attempted to capture the invariants necessary for the download of a single target to be legal. It would be worthwhile to include it here. Also, pedantically comment it because `.tla` files and even their `.pdf` output can be nigh impossible to read for non-specialists.

Current behavior for of a `Client` (and in a few places `Tuf`) is to follow the Exactly One Happy Path as described in the spec. We can do better than this.

**Comment by erickt** [comment]
Hello! Did you ever make progress on this? If not, would you still be interested in uploading it in a branch? I'd love to check it out.

**Comment by heartsucker** [comment]
I don't have it. It was something I was working on at a previous job, and I didn't have time to finish it. I also don't even know if I have access to the start of the model either :neutral_face:

**Comment by erickt** [comment]
No worries! Thanks anyway. I'll close this and the CLI ticket then.
