### ISSUE TITLE
Client never saves remote metadata locally

### ISSUE THREAD

**Issue by erickt** [heartsucker/rust-tuf#153]
It looks like `Client` never actually saves metadata locally. We should fix this so we don't have to hit the remote host all the time.

**Comment by trishankatdatadog** [comment]
Well, not only for efficiency reasons, but you gotta cache the previous metadata to avoid [rollback attacks](https://github.com/theupdateframework/specification/blob/master/tuf-spec.md#5-detailed-workflows).
