### ISSUE TITLE
Spec - 4.5 - Support for delegated target roles

### ISSUE THREAD

**Issue by heartsucker** [heartsucker/rust-tuf#16]

**Comment by heartsucker** [comment]
Work can be tracked on branch `delegations`.

**Comment by heartsucker** [comment]
Reopening because of the rewrite.

**Comment by trishankkarthik** [comment]
Hi! Are you doing breadth-first or depth-first search for delegations? I ask only because I though I saw BFS in a branch before...

**Comment by heartsucker** [comment]
DFS for finding targets in a delegation, but I was doing BFS for updating delegations. However, that commit is long gone as I completely rewrote this over the last two days since I had a shitty internal API that backed me into a corner. Especially for some of the stuff that was needed for rustup.

**Comment by trishankkarthik** [comment]
Thanks for the clarification!

**Comment by heartsucker** [comment]
Blocked by #103

**Comment by heartsucker** [comment]
Requires: #15 #17
