### ISSUE TITLE
Spec - 4.5 - Client must prioritize trust in an ordered fashion given multiple delegations

### ISSUE THREAD

**Issue by heartsucker** [heartsucker/rust-tuf#17]
e.g., the first to appear is the truth

Related: #16

**Comment by heartsucker** [comment]
Spec is unclear on this. Waiting on updates.

**Comment by trishankkarthik** [comment]
Could you explain where it is unclear? We have [how process prioritized / terminating / multi-role delegations](https://github.com/theupdateframework/tuf/blob/8ddc62c43ff05fee53776e54985071bf83a00c89/docs/tuf-spec.txt#L1087-L1111), but I suppose you mean how to write these delegations in the first place?

Cc: @JustinCappos @vladimir-v-diaz

**Comment by heartsucker** [comment]
Ah shit. I think my local copy is out of sync with the latest. At some point it said something like "we are investigating different methods for prioritization" and I thought it still hadn't been resolved. I think the spec actually includes enough of an explanation.

**Comment by heartsucker** [comment]
This was actually closed by the change set from the merge 4844207

**Comment by trishankkarthik** [comment]
In case you need more information, please also see the [Diplomat](https://www.usenix.org/conference/nsdi16/technical-sessions/presentation/kuppusamy) paper. Let us know if you have questions!

**Comment by heartsucker** [comment]
Reopened because of the rewrite.
