### ISSUE TITLE
rust-tuf should preserve unknown fields in metadata

### ISSUE THREAD

**Issue by erickt** [heartsucker/rust-tuf#223]
While the TUF spec explicitly calls out some areas where metadata can be customized (like the target `custom` field), it does not forbid metadata from containing other non-standard fields. For example, python-tuf adds a `keyid_hash_algorithms` field to the root key structure, which is incorporated into that key's key id. rust-tuf currently deserializes metadata into a rust struct, then re-serializes it into cjson in order to validate metadata. Unfortunately though this means that we throw away unknown fields, and therefore will fail to validate the signature.

To fix this, I think we have two options:

1. Rather than directly deserializing some signed metadata like the root metadata into:

```
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SignedMetadata<D, M> {
    signatures: Vec<Signature>,
    #[serde(rename = "signed")]
    metadata: M,
    #[serde(skip_serializing, skip_deserializing)]
    _interchage: PhantomData<D>,
}
```

Instead, we should deserialize into a type that stores the signed metadata in a `serde_json::Object`, which can represent any json value. So something like this:

```
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SignedMetadata<D, M> {
    signatures: Vec<Signature>,
    signed: serde_json::Value,
    #[serde(skip_serializing, skip_deserializing)]
    metadata: Option<M>,
    #[serde(skip_serializing, skip_deserializing)]
    _interchage: PhantomData<D>,
}
```

This structure then is what is serialized to disk, and the `signed` portion is used to validate the signature. Once validated, the `signed` portion can be deserialized into the in memory `metadata` field for further use.

2. We could annotate all structs with [`#[serde(flatten)]`](https://serde.rs/attr-flatten.html) to capture unknown values into a side structure. This then should preserve those values in order to pass validation, but has the side effect of adding a lot of fields, and it might be easy to forget to capture or propagate these fields everywhere, so I think option 1 might be a more robust implementation.

**Comment by trishankatdatadog** [comment]
Haven't thought deeply about it, but sounds like a good idea to check the signature on the signed object with any structure first, before then going on to parse the signed object into a specific structure.

**Comment by heartsucker** [comment]
I think we might want to go another route and use the `shims` again.The struct we pass around for actually doing TUF operations would contain a `raw: JsonValue` but all the fields would actually exist in the "normal" way to that we get type safety. For example:

```rust
/// Metadata for the root role.
#[derive(Debug, Clone, PartialEq)]
pub struct RootMetadata {
    version: u32, 
    expires: DateTime<Utc>,
    consistent_snapshot: bool,
    keys: HashMap<KeyId, PublicKey>,
    root: RoleDefinition,
    snapshot: RoleDefinition,
    targets: RoleDefinition,
    timestamp: RoleDefinition,
    raw: JsonValue,      // <--------- added
}
```

When we serialize again, the raw value is updated to include values that changed. The rules for this could be merges for maps to ensure extra keys are kept, but other values are overwritten.

**Comment by erickt** [comment]
Unfortunately we can't just use `serde_json::Value`, because by default it deserializes values into a `BTreeMap`, which may change the field ordering. serde_json does have a `preserve_order` feature, which should fix this, but unfortunately features are additive, so enabling this feature would also cause all of Fuchsia to switch over to indexed maps. I need to do some research on this.

**Comment by heartsucker** [comment]
Maybe just save the raw bytes? That's not the prettiest thing, but it would definitely work.
