### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by owen-vromans** [heartsucker/rust-tuf#399]
Or is it still being worked on?

**Comment by znewman01** [comment]
I think you have your answer :(

https://github.com/awslabs/tough is not an *official* TUF project but it is currently active; you may have more success there.

**Comment by erickt** [comment]
Hey! Sorry, I missed your question. We're using it in production on Fuchsia, but we haven't needed a specific feature, or ran into any bugs, so I haven't been iterating on it. It's production-ready, I just keep forgetting to cut a proper 0.3 release for it.

**Comment by znewman01** [comment]
Sorry to prematurely declare your death, @erickt :) Great to hear!

**Comment by erickt** [comment]
@znewman01 no worries! I'm going to close this ticket for now, but please file any new tickets if you run into issues, or any PRs that I'd be happy to review.
