### ISSUE TITLE
Relicense to dual MIT/Apache-2.0

### ISSUE THREAD

**Issue by heartsucker** [heartsucker/rust-tuf#56]
I would like to dual license this project to MIT/Apache-2.0. This issue is here to ensure that all previous contributors consent to these changes.

The following contributors will need to complete the below task before this ticket can be resolved.

- [ ] @briansmith
- [ ] @kamalmarhubi
- [ ] @sgrif
- [x] @vks
- [x] @zmanian

Please make a PR to the branch `relicense` with an empty commit with this message. Please GPG sign this commit (if you can). Please tag this issue in your PR.

```
consent to relicense

I consent to the relicensing of my past contributions to the MIT/Apache2.0 dual license as described in the files LICENSE-MIT and LICENSE-APACHE
```

**Comment by sgrif** [comment]
I've only touched the README, you don't need my consent.

**Comment by heartsucker** [comment]
@sgrif I am no legal expert and don't know enough about copyright law in the several relevant countries, so could you please make a PR into the repo just to cover my ass for all of eternity? :)

**Comment by briansmith** [comment]
@heartsucker You can use and distribute the code I submitted in PR #41 under the MIT/Apache license.
