### ISSUE TITLE
Current root metadata update scheme doesn't support post-compromise rollbacks

### ISSUE THREAD

**Issue by heartsucker** [heartsucker/rust-tuf#64]
In the event of bad metadata, the client needs to rebuild the chain back from scratch. Imagine this

```
Good keys: A -> B -> C --------------------> D
Bad keys:            | -> D' -> E' -> F'
```

Metadata/keys `D` could never be reached because the client can't hop from `F'` to `D`. Client need to know how to roll back and untrust metadata.

**Comment by trishankkarthik** [comment]
This is true. However, as @JustinCappos observed, once bad keys have been used to cause a client to install malware, it's going to be difficult to roll back and untrust metadata. The only surefire way is to "nuke from orbit" (i.e., destroy and rebuild container or virtual machine).

**Comment by vladimir-v-diaz** [comment]
Do we "nuke from orbit" if a lowly developer role is compromised and malware is installed?

**Comment by heartsucker** [comment]
Consider the scenario where something like `apt-get update` is run, but no packages are installed. That doesn't need to be nuked from orbit. Or, if a package is installed but never executed.

I guess [this part](https://github.com/theupdateframework/tuf/blob/develop/docs/tuf-spec.txt#L1147-L1157) of the spec made it sound like rollbacks are a possibility, but I may have read it wrong. If indeed I read it wrong, can we polish and merge https://github.com/theupdateframework/tuf/pull/455 and really nail down the exact behavior in all situations?

> Do we "nuke from orbit" if a lowly developer role is compromised and malware is installed?

I was only talking about the root metadata since that is the exceptional case with regards to updating/rolling back.

**Comment by vladimir-v-diaz** [comment]
The spec states that Timestamp and Snapshot metadata must be deleted in the event of a fast-forward attack for any role.

> 1.8. **If the the timestamp and / or snapshot keys have been rotated, then
>     delete the previous timestamp and snapshot metadata files.** This is done
>     in order to recover from fast-forward attacks after the repository has been
>     compromised and recovered. A _fast-forward attack_ happens when attackers
>     arbitrarily increase the version numbers of: (1) the timestamp metadata,
>     (2) the snapshot metadata, and / or (3) the targets, or a delegated
>     targets, metadata file in the snapshot metadata. Please see [the submitted
>     Mercury
>     draft](https://ssl.engineering.nyu.edu/papers/kuppusamy_usenix_17.pdf) for
>     more details.

https://github.com/theupdateframework/tuf/blob/b3b5f6348c6fd6f8c21dc1c7ae430888c58fb1b4/docs/tuf-spec.txt#L994-L1003

**Comment by vladimir-v-diaz** [comment]
* Timestamp and Snapshot must be deleted if keys are rotated (this might happen to recover from a fast-forward attack).

**Comment by heartsucker** [comment]
@vladimir-v-diaz Yeah, that part I understood and is already covered [here](https://github.com/heartsucker/rust-tuf/blob/b4a85732bce8114772f115e32e0b858ef14a0d0d/src/tuf.rs#L276-L281).

This issue was only meant to track whether or not recovery is possible if there is a root compromise.

**Comment by vladimir-v-diaz** [comment]
Oh, I see.  We should edit the specification to explain what should happen if a threshold of keys are compromised.

We can say something like:
"If less than a threshold of Root keys are compromised, the repository administrators should revoke trust on the compromised keys.  This can be accomplished with a normal rotation of root keys, covered in section 6.1 (key management and migration). If a threshold of root keys are compromised, then "root.json" should be updated out-of-band, however the threshold should be chosen so that this is extremely unlikely."

I agree with Trishank and Justin, it might not be possible to safely recover from a complete compromise of all the Root keys.

**Comment by heartsucker** [comment]
> it might not be possible to safely recover from a complete compromise of all the Root keys

This actually makes things easier on my side. Ha. Closing.

**Comment by vladimir-v-diaz** [comment]
![](http://s2.quickmeme.com/img/ba/bac1f010aec03443fad2147dd550772b9a62083aaa7ffd9492e035c7a86750f1.jpg)

[stealing Trishank's idea]
