### ISSUE TITLE
Create "metadata_root" option that allows metadata to stored somewhere other than the root

### ISSUE THREAD

**Issue by heartsucker** [heartsucker/rust-tuf#69]
Given a repo at `url://path/to/tuf`, allow all metadata to be prefixed with a relative path to not pollute the repo root with tons of consistent snapshot metadata.

For example:

```
path/to/tuf/
  | -- metadata/
  |     | -- root.json
  |  -- targets/
        | -- some_target.tgz
```

This *technically* breaks the spec, in way that doesn't damage any of the security guarantees. It also allows for easier managing of caching on CDNs. Putting a delegation on the same path to the target, (e.g., `crates/serde/*` being delegated to role `crates/serde` and putting that under `crates/serde.json`) means that caching rules get complex.

@trishankkarthik, this may be of interest to you.

**Comment by heartsucker** [comment]
Linking to https://github.com/theupdateframework/taps/issues/34 as a possible solution to this instead.

**Comment by trishankkarthik** [comment]
Busy writing my thesis! Let me get back to you as soon as possible...
