### ISSUE TITLE
Don't encode ed25519 keys as HEXLOWER

### ISSUE THREAD

**Issue by heartsucker** [heartsucker/rust-tuf#78]
That's in the spec, but it's just bananas. We should use something like PKCS#8.

**Comment by heartsucker** [comment]
Related #66

**Comment by tarcieri** [comment]
For what it's worth, so long as you're working with JSON, I personally find structured JSON and a hex encoding less "bananas" then taking an ASN.1 representation, encoding it in DER, placing it in a PEM wrapper, then shoving that into a JSON string...

**Comment by heartsucker** [comment]
I'm trying to abstract away from JSON a bit, and this is mostly relevant to #79 which was never done in a simple way according to the spec.

**Comment by tarcieri** [comment]
To be clear, I'm not saying PKCS#8 is bad, but I do wonder if there's something cleaner to be done encapsulating DER in a JSON string than PEM-in-a-JSON-string

**Comment by trishankkarthik** [comment]
Paging @vladimir-v-diaz who works on this in TUF

**Comment by vladimir-v-diaz** [comment]
@heartsucker
Why PKCS#8?  Isn't PKCS#8 meant for private key information?

I agree with @tarcieri.  If possible, it would be nice if Ed25519 public keys can be read/parsed from metadata in the simplest manner possible.  Ideally, we should land on a format/encoding that can be parsed by most libraries or languages and minimize the number of dependencies.

For instance, in the reference implementation I am hoping to use pure python to decode the Ed25519 public key in metadata to get to the raw 32-byte key.  It doesn't matter to me if it's base64, base16, hex- encoded, but an encoding/format that is widely supported is ideal.

However, implementations should be free to store public/private keys in whatever complex format they wish.

**Comment by briansmith** [comment]
I think two things are being conflated in the discussion above.

One: How should the private key be stored? I think PKCS#8 is fine for that considering that it's the only format even close to being a standard that works for all key types, and considering that it actually has the necessary metadata to distinguish, say, a Ed25519 key from a P-256 key.

Two: How should the public key be encoded? My understanding is that TUF already specifies formats and IMO it's probably better to just use the formats TUF recommends.

**Comment by heartsucker** [comment]
>  Why PKCS#8? Isn't PKCS#8 meant for private key information?

Yeah, I should have been more clear. I mean the ASN.1 subset of PKCS#8 that describes the public key. I really just want this lib to deal with one common public key format, and I don't want that format to be heavily dependent on JSON.

At the lib level, using the current encoding rules doesn't make sense because it means that if (in theory) someone implements this so that some given application serves TUF files in both JSON *and* DER, then one wouldn't be able to compare keys easily since key IDs are `sha256(cjson(encode(pub_bytes)))`. If everything is in the SPKI format or PKCS#8 subset / pub key format, and key IDs are `sha256(spki_bytes)`, then there is a semantically meaningful translation from JSON to DER.

> For instance, in the reference implementation I am hoping to use pure python to decode the Ed25519 public key in metadata to get to the raw 32-byte key. It doesn't matter to me if it's base64, base16, hex- encoded, but an encoding/format that is widely supported is ideal.

Yeah, sure. That's reasonable, but the spec implies that no two TUF implementations have to be able to talk to each other. For example, I might choose to only use SHAKE128 as my hash alg for targets, and if some other lib doesn't use that, then we'll never be able to talk to each other. Or if I choose a particular curve to signing keys. Or only 8192 bit RSA keys.

I'm trying to keep this as independent as possible from the oddities of JSON and CJSON as defined in the original spec.

**Comment by vladimir-v-diaz** [comment]
I suppose we'll change the way key IDs are generated once we generalize the format of Metadata documents.

@heartsucker 
The key ID might end up being something like HASH(`key_entry`), where `key_entry` can be in DER, JSON, CJSON, PKCS#8, base64 encoding, or whatever format.  We can let implementors decide the actual content of `key_entry`, but the specification can provide an example of what it may contain and explain why one should avoid key ID collisions.

An interesting point you bring up is the idea of an application that serves TUF files in multiple formats, simultaneously.  If the application supports both JSON and DER, it can presumably match the key ID for one format to another by doing the calculation/conversion.  For example, if a delegated role generates its key ID in DER "mode" but a delegator lists it in JSON, the application can simply use `key_entry` to generate the key ID in the delegator's expected mode.  Or one can avoid this entirely by not supporting multiple metadata extensions or using a standard format that works across any metadata extension.

**Comment by tarcieri** [comment]
Thought I'd take this opportunity to note I'm working on a way to produce content hashes which are identical across encodings, which sounds ideal for this sort of use case.

Not completely ready to talk about my stuff, but what I'm doing is nearly identical to @benlaurie's objecthash:

https://github.com/benlaurie/objecthash

**Comment by briansmith** [comment]
> I mean the ASN.1 subset of PKCS#8 that describes the public key

This is `SubjectPublicKeyInfo`, often abbreviated as SPKI.
