### ISSUE TITLE
Change string encoding of hash digests to base64

### ISSUE THREAD

**Issue by heartsucker** [heartsucker/rust-tuf#83]

**Comment by heartsucker** [comment]
This actually might be problematic for consistent snapshots as it would make it annoying to write files to the local FS or address them over HTTP. This could of course be worked around.

**Comment by tarcieri** [comment]
Are you saying because Base64 isn't URL safe or safe as a filename? Using Base64url would solve both of those problems (I would suggest always using Base64url for that reason)

**Comment by heartsucker** [comment]
Both because they would lead to weird addressing of info that wouldn't exactly match up to what's expected when translating things everywhichway. So yes, b64url would work. Just leaving this here as a note to myself because I was working on something unrelated.

**Comment by heartsucker** [comment]
Closed by 6a07986
