### ISSUE TITLE
tuf/remote: upgrade hyper to 0.11

### ISSUE THREAD

**Issue by lucab** [heartsucker/rust-tuf#98]
This crate uses and directly exposes structs from hyper-0.10. A new major 0.11 async version of hyper has been released in the meanwhile.

I understand the amount of changes could be quite large, but you have an hyper version bump on your roadmap?

**Comment by heartsucker** [comment]
I only call hyper in a couple of places, so this should be an easy fix. Is this something you'd like to tackle?

**Comment by lucab** [comment]
However the changes in 0.11 are pretty big, a few things have been removed (proxy, redirection, etc.) and most of the remote internals will have to be switched to futures-based logic.

At the moment I'm not yet familiar enough (and don't have much time) to do this myself, but I was wondering if you already started looking at it.

**Comment by heartsucker** [comment]
I have not looked at it yet as the current version should be sufficient to get this into rustup which is my current target. If they move to `0.11` before I can wedge this in, I can update too.

**Comment by vks** [comment]
I believe this can be closed. The crate depends on hyper 0.12 now.

**Comment by lucab** [comment]
Indeed, thanks for the heads-up!
